[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.19.1",
    "boto3>=1.43.73",
    "fastapi[standard]>=0.141.1",
    "mangum>=0.21.0",
    "psycopg[binary]>=3.3.4",
    "sqlalchemy>=2.0.52",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
