"""add_level_certificates_to_doctors

Revision ID: e41d28c8a1b4
Revises: 13b74fb4c3de
Create Date: 2026-08-19 01:25:37.289722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e41d28c8a1b4'
down_revision: Union[str, Sequence[str], None] = '13b74fb4c3de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('level', sa.String(), nullable=True))
    op.add_column('doctors', sa.Column('certificates', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctors', 'certificates')
    op.drop_column('doctors', 'level')
    # ### end Alembic commands ###
