"""add_level_certificates_to_doctors

Revision ID: e89f4a2ea0aa
Revises: e41d28c8a1b4
Create Date: 2026-08-19 01:28:47.893324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e89f4a2ea0aa'
down_revision: Union[str, Sequence[str], None] = 'e41d28c8a1b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
